import urllib.parse

from youtube_transcript_api import YouTubeTranscriptApi
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage

from backend.state import BlogState
backend/nodes.py

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.7,
)


def extract_transcript(state: BlogState) -> BlogState:
    """Extract the YouTube video ID and fetch its transcript."""

    url = state.get("youtube_url", "")

    try:
        # Parse the video ID from standard or shortened YouTube URLs
        parsed = urllib.parse.urlparse(url)

        if "youtu.be" in parsed.netloc:
            video_id = parsed.path.lstrip("/").split("/")[0]
        else:
            video_id = urllib.parse.parse_qs(
                parsed.query
            ).get("v", [None])[0]

        if not video_id:
            return {
                "error": "Could not extract video ID from URL."
            }

        ytt_api = YouTubeTranscriptApi()

        transcript = ytt_api.fetch(video_id)

        text = " ".join(
            snippet.text
            for snippet in transcript
        )

        return {
            "video_id": video_id,
            "transcript": text,
            "error": None,
        }

    except Exception as e:
        return {
            "error": f"Failed to extract transcript: {str(e)}"
        }


def generate_outline(state: BlogState) -> BlogState:
    """Generate a structured blog outline using Gemini."""

    if state.get("error"):
        return state

    transcript = state["transcript"]

    prompt = f"""
Create a structured, engaging blog outline based on the
following YouTube video transcript.

Requirements:
- Identify the main topic and key ideas.
- Create a logical H1/H2/H3 structure.
- Preserve important technical details.
- Do not invent information that is not supported by the transcript.
- Make the outline suitable for a high-quality blog post.

Transcript:

{transcript[:15000]}
"""

    response = llm.invoke(
        [HumanMessage(content=prompt)]
    )

    return {
        "outline": response.content
    }


def write_blog(state: BlogState) -> BlogState:
    """Generate the final Markdown blog using Gemini."""

    if state.get("error"):
        return state

    transcript = state["transcript"]
    outline = state["outline"]

    system_msg = SystemMessage(
        content="""
You are an expert content marketer and technical blog writer.

Your job is to transform YouTube video content into a
high-quality, original blog post.

Rules:
- Write clean Markdown.
- Use a clear title.
- Use appropriate H2 and H3 headings.
- Make the article easy to read.
- Preserve factual accuracy.
- Do not invent facts, statistics, quotes, or claims.
- Use the transcript as the source of truth.
- Do not mention that the article was generated by AI.
"""
    )

    prompt = f"""
Write a comprehensive blog post based on the following outline.

OUTLINE:
{outline}

TRANSCRIPT:
{transcript[:15000]}

Return only the final Markdown blog post.
"""

    response = llm.invoke(
        [
            system_msg,
            HumanMessage(content=prompt),
        ]
    )

    return {
        "final_blog": response.content
    }
